package(default_visibility = ["//visibility:public"])

exports_files(["bootstrap.lua"])

cc_library(
	name = "cowgol_lib",
	srcs = [
		"cowgol.c",
		"cowgol.h"
	],
	copts = ["-std=c1x"],
    includes = [""],
)

