#!/bin/sh
set -e

options=$(getopt -s sh -n $0 o: "$@")
if [ $? -ne 0 ]; then
    echo >&2 "Usage: $0 [-o outputfile] inputfiles..."
    exit 1
fi

output=${1%.*}
for option in $options; do
    case "$option" in
        -o) shift; output=$1; shift;;
        --) break;;
    esac
done

./bootstrap/bootstrap.lua "$@" > $output.c
gcc -g -O -std=c1x -fms-extensions -o $output $output.c -I bootstrap bootstrap/cowgol.c
