package(default_visibility = ["//visibility:public"])

sh_binary(
    name = "bbctube_test",
    srcs = ["bbctube_test.sh"],
    data = [
        "//scripts:stupid_test",
        "//emu/bbctube"
    ],
)
