#!/bin/sh

libbindir=/opt/packages/cowgol/lib.bin
sharedir=/opt/packages/cowgol/share

set -x
$libbindir/init
$libbindir/tokeniser2 \
    $sharedir/fuzixz80/runtime.cow \
    $sharedir/z80/runtime.cow \
    $sharedir/fuzixz80/syscalls.cow \
    $sharedir/fuzixz80/wrappedsys.cow \
    $sharedir/common/runtime.cow
$libbindir/parser
$libbindir/tokeniser2 "$@"
$libbindir/parser
$libbindir/typechecker
(mv iops-out.dat iops.dat || exit 0)
$libbindir/backendify
(mv iops-out.dat iops.dat || exit 0)
$libbindir/classifier
$libbindir/blockifier
(mv iops-out.dat iops.dat || exit 0)
$libbindir/codegen
(mv iops-out.dat iops.dat || exit 0)
$libbindir/placer
(mv iops-out.dat iops.dat || exit 0)
$libbindir/emitter
