#!/bin/sh

tmpdir=/tmp/$$.mkdist
trap "rm -rf $tmpdir" EXIT
mkdir -p $tmpdir

exes=$(find bin/fuzixz80 -type f ! -name "*.log")
install -D -t $tmpdir/opt/packages/cowgol/lib.bin/ $exes
install -D -t $tmpdir/opt/packages/cowgol/bin/ scripts/fuzix/cowgol
install -D -t $tmpdir/opt/packages/cowgol/share/fuzixz80/ src/arch/fuzixz80/lib/*.cow
install -D -t $tmpdir/opt/packages/cowgol/share/fuzixz80/ src/arch/z80/lib/*.cow
install -D -t $tmpdir/opt/packages/cowgol/share/fuzixz80/ src/arch/common/lib/*.cow

tar -C $tmpdir --create -f $PWD/$1 --format=v7 .
