#!/bin/sh
set -e

options=$(getopt -s sh -n $0 ko: "$@")
if [ $? -ne 0 ]; then
    echo >&2 "Usage: $0 [-k] [-o outputfile] inputfiles..."
    exit 1
fi

output=${1%.*}
for option in $options; do
    case "$option" in
        -o) shift; output=$(realpath -s $1); shift;;
        --) break;;
    esac
done

./bootstrap/bootstrap.lua "$@" > $output.c
gcc -g -Og -std=c1x -fms-extensions -ffunction-sections -fdata-sections \
  -o $output $output.c -I bootstrap bootstrap/cowgol.c
