#!/bin/sh
set -e

COWGOL_INIT=$(realpath -s ${COWGOL_INIT-$bindir/init})
COWGOL_TOKENISER=$(realpath -s ${COWGOL_TOKENISER-$bindir/tokeniser2})
COWGOL_PARSER=$(realpath -s ${COWGOL_PARSER-$bindir/parser})
COWGOL_TYPECHECKER=$(realpath -s ${COWGOL_TYPECHECKER-$bindir/typechecker})
COWGOL_BACKENDIFY=$(realpath -s ${COWGOL_BACKENDIFY-$bindir/backendify})
COWGOL_CLASSIFIER=$(realpath -s ${COWGOL_CLASSIFIER-$bindir/classifier})
COWGOL_BLOCKIFIER=$(realpath -s ${COWGOL_BLOCKIFIER-$bindir/blockifier})
COWGOL_CODEGEN=$(realpath -s ${COWGOL_CODEGEN-$bindir/codegen})
COWGOL_PLACER=$(realpath -s ${COWGOL_PLACER-$bindir/placer})
COWGOL_EMITTER=$(realpath -s ${COWGOL_EMITTER-$bindir/emitter})

syntax() {
    echo "Syntax: cowgol -a arch [-k] -o outputfile inputfiles..."
    exit 1
}

verbose=no
if [ "$1" = "-v" ]; then
    shift
    verbose=yes
fi

if [ "$1" != "-a" ]; then
    syntax
else
    arch=$2
    shift
    shift
fi

if [ "$1" = "-k" ]; then
    shift
    tmpdir=.
    keep=yes
else
    tmpdir=$(mktemp -d --tmpdir cowgol.XXXXXX)
    trap 'rm -rf $tmpdir' EXIT
    keep=no
fi

if [ "$1" != "-o" ]; then
    syntax
else
    outputfile=$(realpath -s $2)
    shift
    shift
fi

srcs=$(realpath -s "$@")

set +e
(
    set -e
    cd $tmpdir
    $COWGOL_INIT
    $COWGOL_TOKENISER $srcs
    $COWGOL_PARSER
    cp iops.dat iops-parsed.dat
    $COWGOL_TYPECHECKER
    cp iops-out.dat iops-typechecked.dat
    mv iops-out.dat iops.dat
    $COWGOL_BACKENDIFY
    cp iops-out.dat iops-backendified.dat
    mv iops-out.dat iops.dat
    $COWGOL_CLASSIFIER
    $COWGOL_BLOCKIFIER
    cp iops-out.dat iops-blockified.dat
    mv iops-out.dat iops.dat
    $COWGOL_CODEGEN
    cp iops-out.dat iops-codegenned.dat
    mv iops-out.dat iops.dat
    $COWGOL_PLACER
    cp iops-out.dat iops-placed.dat
    mv iops-out.dat iops.dat
    $COWGOL_EMITTER
) 2>&1 >$outputfile.log
result=$?
set -e

if [ $result != 0 -o "$verbose" = "yes" ]; then
    cat $outputfile.log
fi

if [ $result != 0 ]; then
    exit 1
fi

if [ "$keep" = "no" ]; then
    mv $tmpdir/cow.out $outputfile
fi
