#!/bin/sh
set -e

if [ "$1" = "-k" ]; then
    shift
    tmpdir=.
    keep=yes
else
    tmpdir=$(mktemp -d --tmpdir cowgol.XXXXXX)
    trap 'rm -rf $tmpdir' EXIT
    keep=no
fi

if [ "$1" != "-o" ]; then
    echo "Syntax: cowgol [-k] -o outputfile inputfiles..."
    exit 1
else
    outputfile=$(realpath -s $2)
    shift
    shift
fi

srcs=$(realpath -s "$@")
bindir=$(realpath -s bin)

cd $tmpdir
$bindir/tokeniser $srcs
$bindir/parser
cp iops.dat iops-parsed.dat
$bindir/typechecker
cp iops-out.dat iops-typechecked.dat
mv iops-out.dat iops.dat
$bindir/classifier
$bindir/codegen
cp iops-out.dat iops-codegenned.dat
mv iops-out.dat iops.dat
$bindir/placer
cp iops-out.dat iops-placed.dat
mv iops-out.dat iops.dat
$bindir/emitter

if [ "$keep" = "no" ]; then
    mv cow.out $outputfile
fi
