#!/bin/sh
set -e

options=$(getopt -s sh -n $0 o: "$@")
if [ $? -ne 0 ]; then
    echo >&2 "Usage: $0 [-o outputfile] inputfiles..."
    exit 1
fi

output=${1%.*}
for option in $options; do
    case "$option" in
        -o) shift; output=$(realpath $1); shift;;
        --) break;;
    esac
done

tmpdir=$(mktemp -d --tmpdir cowgol.XXXXXX)
trap 'rm -rf $tmpdir' EXIT

./bootstrap/bootstrap.lua "$@" > $tmpdir/output.c
gcc -g -Og -std=c1x -fms-extensions -ffunction-sections -fdata-sections \
  -o $output $tmpdir/output.c -I bootstrap bootstrap/cowgol.c
