#!/bin/sh
stdout=/tmp/$$.stdout
stderr=/tmp/$$.stderr
trap "rm -f $stdout $stderr" EXIT

"$@" >$stdout 2>$stderr
if [ $? = 0 ]; then
	exit 0
else
	cat $stdout
	cat $stderr
	echo "$ " "$@"
	exit 1
fi

