#!/bin/sh
out=$PWD/$1

files="\
	a/ed.com \
	a/!license.txt \
	a/testprog.cow \
	a/compile.sub \
	a/!readme.txt \
	a/submit.com \
	b/blockify.com \
	b/string.cow \
	b/runtime1.cow \
	b/parser.com \
	b/iopsh.com \
	b/placer.com \
	b/runtime0.cow \
	b/fcb.cow \
	b/codegen.com \
	b/emitter.com \
	b/fileio.cow \
	b/classify.com \
	b/argv.cow \
	b/runtime2.cow \
	b/typechck.com \
	b/backend.com \
	b/init.com \
	b/tokenise.com \
	b/thingsh.com \
	b/untoken.com \
	"

(cd tools/cpm && rm -f $out && zip -9q $out $files)

